export enum RooneyExpression {
  NEUTRAL = 'NEUTRAL',
  POINTING = 'POINTING',
  POINTING_2 = 'POINTING_2',
  THINKING = 'THINKING',
  CELEBRATORY = 'CELEBRATORY',
  ENCOURAGING = 'ENCOURAGING',
  WINK = 'WINK',
  BLUSHING = 'BLUSHING',
  ROASTING = 'ROASTING',
  CONFUSED = 'CONFUSED',
  CONCERNED = 'CONCERNED',
  DISAPPOINTED = 'DISAPPOINTED',
  SAD = 'SAD',
  SLEEPING = 'SLEEPING',
  ANGRY = 'ANGRY',
}

export const ROONEY_EXPRESSIONS: Record<RooneyExpression, string> = {
  [RooneyExpression.NEUTRAL]: '/rooney/Neutral.png',
  [RooneyExpression.POINTING]: '/rooney/Pointing.png',
  [RooneyExpression.POINTING_2]: '/rooney/Pointing_2.png',
  [RooneyExpression.THINKING]: '/rooney/Thinking.png',
  [RooneyExpression.CELEBRATORY]: '/rooney/Celebratory.png',
  [RooneyExpression.ENCOURAGING]: '/rooney/Encouraging.png',
  [RooneyExpression.WINK]: '/rooney/Wink.png',
  [RooneyExpression.BLUSHING]: '/rooney/Blushing.png',
  [RooneyExpression.ROASTING]: '/rooney/Roasting_or_Smirk.png',
  [RooneyExpression.CONFUSED]: '/rooney/Confused.png',
  [RooneyExpression.CONCERNED]: '/rooney/Concerned.png',
  [RooneyExpression.DISAPPOINTED]: '/rooney/Disappointed.png',
  [RooneyExpression.SAD]: '/rooney/Sad.png',
  [RooneyExpression.SLEEPING]: '/rooney/Sleeping.png',
  [RooneyExpression.ANGRY]: '/rooney/Angry.png',
};
